export const GenerateDataSet_arraysDataSet=[
    {
        "sector_name": "Typical",
        "phase_name": "Replication",
        "stop_parent": null,
        "stop_name": "DNA Replication",
        "cx": 0,
        "cy": 0,
        "description": "DNA Replication",
        "starting_event": "Initiation",
        "ending_event": "DNA replication termination",
        "stop_stakeholder": null,
        "stop_path": null,
        "Related Proteins": null,
        "phase_color": "#3498DB",
        "stop_has_line": "yes",
        "stop_label_position": "up",
        "Notes": null
    },
    {
        "sector_name": "Typical",
        "phase_name": "Transcription",
        "stop_parent": null,
        "stop_name": "Initiation I",
        "cx": 100,
        "cy": 0,
        "description": null,
        "starting_event": "DNA replication termination",
        "ending_event": "Transcription initiated",
        "stop_stakeholder": null,
        "stop_path": "Concurrent",
        "Related Proteins": null,
        "phase_color": "#2ECC71",
        "stop_has_line": "yes",
        "stop_label_position": "down",
        "Notes": null
    },
    {
        "sector_name": "Typical",
        "phase_name": "Transcription",
        "stop_parent": "Initiation I",
        "stop_name": "Nucleosome repositioned",
        "cx": null,
        "cy": null,
        "description": null,
        "starting_event": "DNA replication termination",
        "ending_event": "Nucleosome repositioned",
        "stop_stakeholder": null,
        "stop_path": "Concurrent",
        "Related Proteins": null,
        "phase_color": "#2ECC72",
        "stop_has_line": "yes",
        "stop_label_position": "down",
        "Notes": null
    },
    {
        "sector_name": "Typical",
        "phase_name": "Transcription",
        "stop_parent": "Initiation I",
        "stop_name": "Basal factors bind promoters",
        "cx": null,
        "cy": null,
        "description": null,
        "starting_event": "Nucleosome repositioned",
        "ending_event": "Basal factors bind promoters",
        "stop_stakeholder": null,
        "stop_path": "Concurrent",
        "Related Proteins": null,
        "phase_color": "#2ECC73",
        "stop_has_line": "yes",
        "stop_label_position": "down",
        "Notes": null
    },
    {
        "sector_name": "Typical",
        "phase_name": "Transcription",
        "stop_parent": "Initiation I",
        "stop_name": "Indirect repressor proteins bind",
        "cx": null,
        "cy": null,
        "description": null,
        "starting_event": "Nucleosome repositioned",
        "ending_event": "Indirect repressor proteins bind",
        "stop_stakeholder": null,
        "stop_path": "Optional",
        "Related Proteins": null,
        "phase_color": "#2ECC74",
        "stop_has_line": "yes",
        "stop_label_position": "down",
        "Notes": null
    },
    {
        "sector_name": "Typical",
        "phase_name": "Transcription",
        "stop_parent": "Initiation I",
        "stop_name": "Activators bind to enhancers",
        "cx": null,
        "cy": null,
        "description": null,
        "starting_event": "Nucleosome repositioned",
        "ending_event": "Activators bind to enhancers",
        "stop_stakeholder": null,
        "stop_path": "Concurrent",
        "Related Proteins": null,
        "phase_color": "#2ECC75",
        "stop_has_line": "yes",
        "stop_label_position": "down",
        "Notes": null
    },
    {
        "sector_name": "Typical",
        "phase_name": "Transcription",
        "stop_parent": "Initiation I",
        "stop_name": "Repressor and corepressor bind",
        "cx": null,
        "cy": null,
        "description": null,
        "starting_event": "Nucleosome repositioned",
        "ending_event": "Repressor and corepressor bind",
        "stop_stakeholder": null,
        "stop_path": "Concurrent",
        "Related Proteins": null,
        "phase_color": "#2ECC76",
        "stop_has_line": "yes",
        "stop_label_position": "down",
        "Notes": null
    }
];