const LocalFindStopData_input = {
  sectors: [
    {
      sector_id: 1,
      sector_name: 'Driver',
      phases: [
        {
          phase_id: 1,
          phase_name: 'Permit',
          stops: [
            {
              stop_id: 1,
              stop_name: 'Learners Permit',
              stop_activities: [
                {
                  act_id: 1,
                  act_name: 'Get parental or legal guardian signature',
                  act_description: 'Before submitting form',
                  act_ending_event: 'Get parental or legal guardian signature',
                  act_starting_event: 'Reach minimum age for learners permit',
                  act_path_type: 'Concurrent',
                  act_meta_data: [],
                  act_it_assets: 'N/A',
                  attributes: {
                    tester2: '1',
                    tester5: '3',
                    tester4: '2',
                    'IT Assets': ['a', 'f', 'q', 'g', 'a'],
                  },
                },
                {
                  act_id: 2,
                  act_name: 'Complete two-part permit exam',
                  act_description: 'Taken at the DMV',
                  act_ending_event: 'Complete two-part permit exam',
                  act_starting_event: "Submit DMV application form'Review DMV manual",
                  act_path_type: 'Concurrent',
                  act_meta_data: [],
                  act_it_assets: 'N/A',
                  attributes: {
                    tester2: '1',
                    tester5: '3',
                    tester4: '2',
                    'IT Assets': 'dfas',
                  },
                },
                {
                  act_id: 3,
                  act_name: 'Review DMV manual',
                  act_description: 'Can be found online',
                  act_ending_event: 'Review DMV manual',
                  act_starting_event: 'Reach minimum age for learners permit',
                  act_path_type: 'Concurrent',
                  act_meta_data: [],
                  act_it_assets: 'N/A',
                  attributes: {
                    tester2: '1',
                    tester5: '3',
                    tester4: '2',
                    'IT Assets': 'afsa',
                  },
                },
                {
                  act_id: 4,
                  act_name: 'Pay application fees',
                  act_description: 'Can be paid online',
                  act_ending_event: 'Pay application fees',
                  act_starting_event: 'Reach minimum age for learners permit',
                  act_path_type: 'Concurrent',
                  act_meta_data: [],
                  act_it_assets: 'N/A',
                  attributes: {
                    tester2: '1',
                    tester5: '3',
                    tester4: '2',
                    'IT Assets': 'a',
                  },
                },
                {
                  act_id: 5,
                  act_name: 'Undergo vision screening at DMV office',
                  act_description: 'Tested at the DMV office',
                  act_ending_event: 'Undergo vision screening at DMV office',
                  act_starting_event: 'Reach minimum age for learners permit',
                  act_path_type: 'Concurrent',
                  act_meta_data: [],
                  act_it_assets: 'N/A',
                  attributes: {
                    tester2: '1',
                    tester5: '3',
                    tester4: '2',
                    'IT Assets': 'sad',
                  },
                },
                {
                  act_id: 6,
                  act_name: 'Submit DMV application form',
                  act_description: 'Can be done online',
                  act_ending_event: 'Submit DMV application form',
                  act_starting_event: 'Get parental or legal guardian signature',
                  act_path_type: 'Concurrent',
                  act_meta_data: [],
                  act_it_assets: 'N/A',
                  attributes: {
                    tester2: '1',
                    tester5: '3',
                    tester4: '2',
                    'IT Assets': 'dfds',
                  },
                },
              ],
              cx: 155.5908966064453,
              cy: 80,
              descendant_stop_id: [2],
              stop_styles: {
                stop_has_line: 'yes ',
                stop_label_position: 'down',
              },
              starting_event: 'Reach minimum age for learners permit',
              ending_event: 'Get permit',
              stop_definition: 'Steps taken to get permit',
              sector_id: 1,
              is_beginning_stop: true,
              color: '#83D6DE',
              phase_name: 'Permit',
              phase_id: 1,
            },
          ],
          phase_styles: {
            phase_color: '#83D6DE',
          },
        },
        {
          phase_id: 2,
          phase_name: 'License',
          stops: [
            {
              stop_id: 2,
              stop_name: 'Prepare for license ',
              stop_activities: [
                {
                  act_id: 7,
                  act_name: '45 hours behind-the-wheel practice',
                  act_description: 'Can be done without instructor',
                  act_ending_event: '45 hours behind-the-wheel practice',
                  act_starting_event: 'Get permit',
                  act_path_type: 'Concurrent',
                  act_meta_data: [],
                  act_it_assets: 'N/A',
                  attributes: {
                    tester2: '1',
                    tester5: '3',
                    tester4: '2',
                    'IT Assets': 'gfsgs',
                  },
                },
                {
                  act_id: 8,
                  act_name: 'Drivers education course',
                  act_description: 'Done in person or online',
                  act_ending_event: 'Drivers education course',
                  act_starting_event: 'Get permit',
                  act_path_type: 'Concurrent',
                  act_meta_data: [],
                  act_it_assets: 'N/A',
                  attributes: {
                    tester2: '1',
                    tester5: '3',
                    tester4: '2',
                    'IT Assets': 'asdafa',
                  },
                },
                {
                  act_id: 9,
                  act_name: 'Hold permit for at least 9 months',
                  act_description: 'Since passed permit test',
                  act_ending_event: 'Hold permit for at least 9 months',
                  act_starting_event: 'Get permit',
                  act_path_type: 'Concurrent',
                  act_meta_data: [],
                  act_it_assets: 'N/A',
                  attributes: {
                    tester2: '1',
                    tester5: '3',
                    tester4: '2',
                    'IT Assets': 'hrteh',
                  },
                },
                {
                  act_id: 10,
                  act_name: '16 years and 3 months of age',
                  act_description: '',
                  act_ending_event: '16 years and 3 months of age',
                  act_starting_event: 'Get permit',
                  act_path_type: 'Concurrent',
                  act_meta_data: [],
                  act_it_assets: 'N/A',
                  attributes: {
                    tester2: '1',
                    tester5: '3',
                    tester4: '2',
                    'IT Assets': 'fccb',
                  },
                },
              ],
              cx: 255.5908966064453,
              cy: 80,
              descendant_stop_id: [3],
              stop_styles: {
                stop_has_line: 'yes ',
                stop_label_position: 'up',
              },
              starting_event: 'Get permit',
              ending_event: 'Ready for road test',
              stop_definition: 'Steps taken before exam',
              sector_id: 1,
              is_beginning_stop: false,
              color: '#FCB941',
              phase_name: 'License',
              phase_id: 2,
            },
            {
              stop_id: 3,
              stop_name: 'Drivers license exam',
              stop_activities: [
                {
                  act_id: 11,
                  act_name: 'Backing out of a space',
                  act_description: '',
                  act_ending_event: 'Backing out of a space',
                  act_starting_event: 'Ready for road test',
                  act_path_type: 'Concurrent',
                  act_meta_data: [],
                  act_it_assets: 'N/A',
                  attributes: {
                    tester2: '1',
                    tester5: '3',
                    tester4: '2',
                    'IT Assets': 'sfsv',
                  },
                },
                {
                  act_id: 12,
                  act_name: 'Three point turn',
                  act_description: '',
                  act_ending_event: 'Three point turn',
                  act_starting_event: 'Ready for road test',
                  act_path_type: 'Concurrent',
                  act_meta_data: [],
                  act_it_assets: 'N/A',
                  attributes: {
                    tester2: '1',
                    tester5: '3',
                    tester4: '2',
                    'IT Assets': 'xvwtw',
                  },
                },
                {
                  act_id: 13,
                  act_name: 'Observe right-of-way',
                  act_description: '',
                  act_ending_event: 'Observe right-of-way',
                  act_starting_event: 'Ready for road test',
                  act_path_type: 'Concurrent',
                  act_meta_data: [],
                  act_it_assets: 'N/A',
                  attributes: {
                    tester2: '1',
                    tester5: '3',
                    tester4: '2',
                    'IT Assets': 'fsvx',
                  },
                },
                {
                  act_id: 14,
                  act_name: 'Backing up',
                  act_description: '',
                  act_ending_event: 'Backing up',
                  act_starting_event: 'Ready for road test',
                  act_path_type: 'Concurrent',
                  act_meta_data: [],
                  act_it_assets: 'N/A',
                  attributes: {
                    tester2: '1',
                    tester5: '3',
                    tester4: '2',
                    'IT Assets': 'dst3e',
                  },
                },
                {
                  act_id: 15,
                  act_name: 'Signal and turn',
                  act_description: '',
                  act_ending_event: 'Signal and turn',
                  act_starting_event: 'Ready for road test',
                  act_path_type: 'Concurrent',
                  act_meta_data: [],
                  act_it_assets: 'N/A',
                  attributes: {
                    tester2: '1',
                    tester5: '3',
                    tester4: '2',
                    'IT Assets': 'vsre',
                  },
                },
                {
                  act_id: 16,
                  act_name: 'Parallel parking',
                  act_description: '',
                  act_ending_event: 'Parallel parking',
                  act_starting_event: 'Ready for road test',
                  act_path_type: 'Concurrent',
                  act_meta_data: [],
                  act_it_assets: 'N/A',
                  attributes: {
                    tester2: '1',
                    tester5: '3',
                    tester4: '2',
                    'IT Assets': 'asf xz',
                  },
                },
              ],
              cx: 355.5908966064453,
              cy: 80,
              descendant_stop_id: [4],
              stop_styles: {
                stop_has_line: 'yes ',
                stop_label_position: 'down',
              },
              starting_event: 'Ready for road test',
              ending_event: 'Passed road test',
              stop_definition: 'Things evaluated during exam',
              sector_id: 1,
              is_beginning_stop: false,
              color: '#FCB941',
              phase_name: 'License',
              phase_id: 2,
            },
            {
              stop_id: 4,
              stop_name: 'Drivers license',
              stop_activities: [],
              cx: 455.5908966064453,
              cy: 80,
              descendant_stop_id: [],
              stop_styles: {
                stop_has_line: 'yes ',
                stop_label_position: 'up',
              },
              starting_event: 'Passed road test',
              ending_event: 'Receive license ',
              stop_definition: 'Drivers license typically arrive 2 weeks after passing road test',
              sector_id: 1,
              is_beginning_stop: false,
              phase_name: 'License',
              phase_id: 2,
              color: '#FCB941',
            },
          ],
          phase_styles: {
            phase_color: '#FCB941',
          },
        },
      ],
    },
  ],
};
export { LocalFindStopData_input };
